import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeContainer: {
    backgroundColor: '#f2f2f2',
    width: '100%',
    height: '100%',
  },
  containerLogin: {
    width: '100%',
    height: '100%',
    padding: 10,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  containerPrincipal: {
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  heading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    height: '10%',
    backgroundColor: '#fbd743',
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: 'center',
    shadowColor: '#363b81',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  headingCloseText: {
    color: '#363b81',
    fontWeight: '500',
    fontSize: 18,
  },
  modo: {
    width: '40%',
    flexDirection: 'row',
    height: '100%',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  modoTexto: {
    color: '#363b81',
    fontSize: 15,
    fontWeight: '500',
  },
  pressModo: {
    backgroundColor: 'rgba(54,59,129, 0.6)',
    borderRadius: 100,
    width: '30%',
    height: '50%',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  pressModoIndicator: {
    width: '60%',
    height: '100%',
    backgroundColor: '#363b81',
    borderRadius: 100,
  },
  pokeList: {
    width: '100%',
    height: '90%',
    backgroundColor: 'rgba(251,515, 67, 0.4)',
  },
  titleStyle: {
    color: '#363b81',
    fontSize: 25,
    textAlign: 'center',
  },
  formLogin: {
    alignItems: 'center',
    width: '88%',
    marginTop: 3,
    justifyContent: 'center',
  },
  textInput: {
    height: '100%',
    width: '100%',
    fontSize: 20,
    borderRadius: 12,
    fontWeight: '600',
    color: '#363b81',
    padding: 11,
    paddingLeft: 18,
    flexDirection: 'row',
  },
  inputPass: {
    height: '100%',
    width: '75%',
    fontSize: 20,
    fontWeight: '600',
    color: '#363b81',
    padding: 11,
    paddingLeft: 18,
    flexDirection: 'row',
  },
  pressablePass: {
    width: '25%',
    padding: 2,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
  },
  pressablePassText: {
    textAlign: 'center',
    fontWeight: '400',
    color: '#363b81',
    fontSize: 15,
  },
  passCage: {
    flexDirection: 'row',
    width: '100%',
    borderWidth: 0.6,
    borderColor: '#ff1f1f',
    backgroundColor: 'rgba(251,215,67, 0.6)',
    height: 46,
    marginTop: 15,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pressableStyle: {
    backgroundColor: '#fbd743',
    borderWidth: 1.5,
    borderColor: '#ff1f1f',
    padding: 10,
    width: '100%',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 20,
  },
  textPressable: {
    color: '#363b81',
    fontSize: 26,
    fontWeight: 'bold',
    justifyContent: 'center',
  },
  imagen: {
    width: '100%',
    resizeMode: 'contain',
    alignItems: 'center',
  },
  pressableContainer: {
    width: '80%',
    alignItems: 'center',
  },
  error: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    color: '#ff1f1f',
    fontSize: 18,
    fontWeight: '600',
  },
  containerList: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 30,
  },
  titulo: {
    color: '#363b81',
    fontSize: 30,
    textAlign: 'center',
    fontWeight: '600',
  },
  card: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#fbd743',
    borderWidth: 1,
    borderColor: '#ff1f1f',
    marginHorizontal: 10,
    marginVertical: 5,
    borderRadius: 8,
  },
  cardName: {
    color: '#363b81',
    fontSize: 25,
    fontWeight: 'bold',
  },
  cardImage: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
  },
});
